// react-helloworld/src/App.tsx
import React from 'react';
import './App.css';

class App extends React.Component {
    state = {
        count: 0
    };
    clicked = () => {
        this.setState({count: this.state.count + 1})
    }
    render() {
        return (
            <div className="App">
                <button onClick={this.clicked}>Click count {this.state.count}</button>
            </div>
        );
    }
}
export default App;

// AngularJSHelloWorld/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  count = 0
  btnClicked() {
    this.count++;
  };
}

<div>
  <button (click)="btnClicked()">Click count {{count}}</button>
</div>
